### ISSUE TITLE
如何抓取周边信息

### ISSUE THREAD

**Issue by tylerrrkd** [PENGZhaoqing/HousePricing#11]
Hi

朋友你好

请问如何抓取房源周边信息？

**Comment by PENGZhaoqing** [comment]
先把基础的房屋数据导入项目里，然后用点击抓取周边数据按钮即可

**Comment by tylerrrkd** [comment]
@PENGZhaoqing 好的，谢谢你！
里边调用的是百度地图API吗？

**Comment by PENGZhaoqing** [comment]
是的，百度地图API，几年前做的，现在API不知道还可以不可以

**Comment by tylerrrkd** [comment]
@PENGZhaoqing 可以了哈哈哈。还是可以用的！
