### ISSUE TITLE
项目跑不起来。。。

### ISSUE THREAD

**Issue by scrcherry** [PENGZhaoqing/HousePricing#8]
我想抓取西安教育机构周边信息，可不可以把数据变成西安教育机构的名称，用这个项目完成抓取~
还有这个项目我跑不起来。。。

![default](https://user-images.githubusercontent.com/17891913/33127032-c66143a6-cfc1-11e7-9c13-36c31f0d71e2.PNG)

**Comment by PENGZhaoqing** [comment]
win系统吧, 只有win才会有timezone的错误, 这个要解决还挺麻烦, 之前有问我的, 后来转linux了

都可以,只要能拿到基础数据, 导入到项目里抓取即可, 但是需要调整一些数据库的字段

**Comment by scrcherry** [comment]
好吧 我看 我也得转linux了 真心问题太多~
